changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - eclipse-ecsp
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feature
      exclude:
        labels:
          - dependencies
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
